CREATE TABLE usuarios (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(100),
    email VARCHAR(100),
    senha VARCHAR(100)
);

INSERT INTO usuarios (nome, email, senha) VALUES
('Ana Silva', 'ana.silva@email.com', 'gatinho123'),
('Bruno Costa', 'bruno.costa@email.com', 'pizza4ever'),
('Carla Souza', 'carla.souza@email.com', 'unicornio99'),
('Diego Lima', 'diego.lima@email.com', 'naolembroasenha'),
('Elena Martins', 'elena.martins@email.com', 'abacaxi_naPizza'),
('Felipe Rocha', 'felipe.rocha@email.com', 'meAjuda2025'),
('Gabriela Nunes', 'gabriela.nunes@email.com', 'batidinhaDelicia'),
('Henrique Alves', 'henrique.alves@email.com', 'hulkSmash321'),
('Isabela Ferreira', 'isabela.ferreira@email.com', 'princesaDoCachorro'),
('João Pereira', 'joao.pereira@email.com', 'esqueciDeNovo'),
('Karina Mendes', 'karina.mendes@email.com', 'cafezinhoForte'),
('Lucas Barros', 'lucas.barros@email.com', 'videogame4life'),
('Mariana Carvalho', 'mariana.carvalho@email.com', 'chocolateEhVida'),
('Nicolas Ribeiro', 'nicolas.ribeiro@email.com', 'queijo_com_goiaba'),
('Olivia Gomes', 'olivia.gomes@email.com', 'naoSouRobo99'),
('Pedro Santana', 'pedro.santana@email.com', 'coxinhaTop1'),
('Carlos Alberto', 'carlos.alberto@email.com', 'amoSonegar123'),
('Quintina Dias', 'quintina.dias@email.com', 'minhaGataSeLoga'),
('Rafael Moreira', 'rafael.moreira@email.com', 'dormindoNoTrabalho'),
('Sabrina Castro', 'sabrina.castro@email.com', 'sereia_de_segunda'),
('Thiago Oliveira', 'thiago.oliveira@email.com', 'bobitoFeliz'),
('Ursula Pinto', 'ursula.pinto@email.com', 'tenteiLembrar3x'),
('Vinícius Teixeira', 'vinicius.teixeira@email.com', 'narutoCorreRapido'),
('Wanderley Nascimento', 'wanderley.nascimento@email.com', 'pagodeNaSexta'),
('Xênia Cardoso', 'xenia.cardoso@email.com', 'unicornioRoxo7'),
('Yago Fernandes', 'yago.fernandes@email.com', 'futebolNaDomingo'),
('Zara Monteiro', 'zara.monteiro@email.com', 'brigadeiroDuplo'),
('André Campos', 'andre.campos@email.com', 'naoMexeNoMeuPC'),
('Beatriz Araújo', 'beatriz.araujo@email.com', 'gatosaoMelhores'),
('Caio Vieira', 'caio.vieira@email.com', 'cerveja_gelada01'),
('Daniela Lopes', 'daniela.lopes@email.com', 'principesaNao'),
('Eduardo Freitas', 'eduardo.freitas@email.com', 'traveiNoElevador'),
('Fernanda Azevedo', 'fernanda.azevedo@email.com', 'amorDePastel'),
('Gustavo Cunha', 'gustavo.cunha@email.com', 'homemAranha404'),
('Helena Rodrigues', 'helena.rodrigues@email.com', 'bolacha_recheada'),
('Igor Machado', 'igor.machado@email.com', 'hackerman2025'),
('Juliana Correia', 'juliana.correia@email.com', 'fitnessSoNaSexta'),
('Kevin Sousa', 'kevin.sousa@email.com', 'minecraftPro99'),
('Larissa Cavalcante', 'larissa.cavalcante@email.com', 'fimDeSemana_ja'),
('Marcos Rezende', 'marcos.rezende@email.com', 'barbeiroTop10'),
('Natália Figueiredo', 'natalia.figueiredo@email.com', 'iogurteComGranola'),
('Orlando Peixoto', 'orlando.peixoto@email.com', 'aposentadoFeliz1'),
('Patricia Guimarães', 'patricia.guimaraes@email.com', 'shoppingNaSabado'),
('Quirino Medeiros', 'quirino.medeiros@email.com', 'nomeEstranhoEuSei'),
('Renata Borges', 'renata.borges@email.com', 'tapiocaSemGluten'),
('Sergio Lacerda', 'sergio.lacerda@email.com', 'chefaoDoExcel'),
('Tatiane Melo', 'tatiane.melo@email.com', 'reuniaoDeNovo_nao'),
('Ulisses Farias', 'ulisses.farias@email.com', 'odeioBoleto99'),
('Vanessa Queiroz', 'vanessa.queiroz@email.com', 'cachorroFofo123'),
('William Brito', 'william.brito@email.com', 'segundaFeiraFim');